# Generated by Django 4.0 on 2022-01-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_band_listing_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.ImageField(default='.static/assets/img/groupe_random.png', upload_to=None),
            preserve_default=False,
        ),
    ]
