# Generated by Django 4.0 on 2022-01-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_band_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.ImageField(default='assets/img/groupe_random.jpg', upload_to=None),
            preserve_default=False,
        ),
    ]
