# Generated by Django 4.0 on 2022-01-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listing_image_alter_band_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
    ]
