# Generated by Django 4.0 on 2022-01-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_remove_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='assets/img/objects_music.png', upload_to='assets/img/'),
            preserve_default=False,
        ),
    ]
